### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by JIeCoRyI3** [AntonBurchak/React-daily-task-manager#3]

**Comment by JIeCoRyI3** [comment]
.idea/
.vscode/
node_modules/
build
 ------ unnecessary line for us ------ .DS_Store
*.tgz
 ------ unnecessary line for us ------ my-app*
 ------ unnecessary line for us ------ template/src/__tests__/__snapshots__/
 ------ unnecessary line for us ------ lerna-debug.log
npm-debug.log*
 ------ unnecessary line for us ------ yarn-debug.log*
 ------ unnecessary line for us ------ yarn-error.log*
 ------ unnecessary line for us ------ /.changelog
.npm/
 ------ unnecessary line for us ------ yarn.lock

**Comment by AntonBurchak** [comment]
Updated.
